msm_serial_hs: add missing include drivers/built-in.o: In function `enable_wakeup_interrupt': sensors_ssc.c:(.text+0x17fc9c): undefined reference to `udelay' sensors_ssc.c:(.text+0x17fc9c): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `udelay' Signed-off-by: YaroST12 <yaro330@gmail.com>